volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    env_file: .env
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  nginx:
    build: ./docker/nginx/
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - static:/static
      - media:/media