# Generated by Django 5.0.4 on 2024-07-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
